[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
    "pip install -r backend/requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "cd backend && python manage.py collectstatic --noinput"
]

[start]
cmd = "cd backend && python manage.py migrate && python manage.py loaddata src/core/fixtures/initial_data.json && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
