# Generated by Django 5.2.16 on 2026-07-13 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mahalla_name', models.CharField(max_length=255, verbose_name='Mahalla nomi')),
                ('district', models.CharField(default='Asaka', max_length=100, verbose_name='Tuman')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yetakchi profili',
                'verbose_name_plural': 'Yetakchilar profillari',
            },
        ),
        migrations.CreateModel(
            name='KPITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('1_ijro', '1. Ijro intizomi (Max: 20 ball)'), ('2_balans', '2. Yoshlar balansi (Max: 5 ball)'), ('3_bandlik', '3. Yoshlar bandligini ta’minlash (Max: 15 ball)'), ('4_bosh_vaqt', '4. Yoshlarning bo‘sh vaqtini mazmunli tashkil etish (Max: 15 ball)'), ('5_profilaktika', '5. Ijtimoiy profilaktika tadbirlari (Max: 10 ball)'), ('6_murojaat', '6. Murojaatlar bilan ishlash (Max: 5 ball)'), ('7_brend', '7. Brend loyihalar va Shaxsiy rivojlanish (Max: 10 ball)'), ('8_talim', '8. Ta’lim muassasalaridagi yoshlar bilan ishlash (Max: 5 ball)'), ('9_startap', '9. Zamonaviy kasblar va startap loyihalar (Max: 5 ball)'), ('10_nomenklatura', '10. Nomenklatura hujjatlar (Max: 10 ball)')], max_length=50, verbose_name="Yo'nalish turi")),
                ('status', models.CharField(choices=[('sariq', 'Kutilmoqda (Sariq)'), ('yashil', 'Tasdiqlandi (Yashil)'), ('qizil', 'Rad etildi (Qizil)')], default='sariq', max_length=20, verbose_name='Status')),
                ('score', models.FloatField(default=0.0, verbose_name='Berilgan ball')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Admin izohi (Rad etish sababi)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('month', models.DateField(help_text='Reyting hisoblanayotgan oy (masalan, 2026-07-01)', verbose_name='Hisobot oyi')),
                ('text_comment', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha izoh (Text field)")),
                ('event_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tadbir nomi')),
                ('event_type', models.CharField(blank=True, choices=[('sport', 'Sport'), ('kibersport', 'Kibersport'), ('musiqa', 'Musiqa'), ('manaviy', 'Ma’naviy-ma’rifiy'), ('boshqa', 'Boshqa')], max_length=50, null=True, verbose_name='Tadbir turi')),
                ('youth_count', models.IntegerField(blank=True, null=True, verbose_name='Qatnashgan yoshlar soni')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Joy nomi')),
                ('event_time', models.DateTimeField(blank=True, null=True, verbose_name='Tadbir vaqti')),
                ('profilaktika_type', models.CharField(blank=True, choices=[('suhbat', 'Profilaktik suhbat'), ('pq1', 'PQ-1 hujjat kiritish')], max_length=50, null=True, verbose_name='Profilaktika turi')),
                ('student_fio', models.CharField(blank=True, max_length=255, null=True, verbose_name="O'quvchining Ism Familiyasi")),
                ('startup_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Startap nomi')),
                ('startup_owner_fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Startapchi F.I.O')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.profile', verbose_name='Yetakchi')),
            ],
            options={
                'verbose_name': 'KPI Topshiriq',
                'verbose_name_plural': 'KPI Topshiriqlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='kpi_uploads/%Y/%m/', verbose_name='Fayl yoki Rasm (PDF/JPG/PNG)')),
                ('is_image', models.BooleanField(default=False, verbose_name='Bu rasmmi?')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.kpitask', verbose_name='Topshiriq')),
            ],
            options={
                'verbose_name': 'Ilova fayl',
                'verbose_name_plural': 'Ilova fayllari',
            },
        ),
    ]
