# Generated by Django 5.2.16 on 2026-07-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpitask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kpitask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
