# Generated by Django 5.2.16 on 2026-07-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_kpitask_created_at_alter_kpitask_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Kalit (masalan: 1_ijro)')),
                ('label', models.CharField(max_length=200, verbose_name="Yo'nalish nomi")),
                ('max_score', models.PositiveIntegerField(verbose_name='Maksimal ball')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib raqami')),
                ('admin_scored', models.BooleanField(default=False, verbose_name='Admin tomonidan baholanadi')),
                ('is_uploadable', models.BooleanField(default=True, verbose_name='Foydalanuvchi fayl yuklashi mumkin')),
                ('info', models.TextField(blank=True, verbose_name="Qisqacha ma'lumot")),
                ('how', models.TextField(blank=True, verbose_name='Qanday bajarish kerak')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "KPI Yo'nalish",
                'verbose_name_plural': "KPI Yo'nalishlar",
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='kpitask',
            name='direction',
            field=models.CharField(max_length=50, verbose_name="Yo'nalish turi"),
        ),
    ]
