# Generated by Django 5.2.16 on 2026-07-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial_directions'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIMonthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction_key', models.CharField(max_length=30)),
                ('month', models.DateField()),
                ('target_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Oylik Reja',
                'verbose_name_plural': 'Oylik Rejalar',
                'ordering': ['month', 'direction_key'],
                'unique_together': {('direction_key', 'month')},
            },
        ),
    ]
