# Generated by Django 5.2.16 on 2026-07-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_kpimonthplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='photo_taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rasm olingan vaqt (EXIF)'),
        ),
    ]
