# Generated by Django 5.2.11 on 2026-07-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_taskattachment_photo_taken_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpimonthplan',
            name='plan_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
