# Generated by Django 5.2.16 on 2026-07-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_plan_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpidirection',
            name='default_target',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="0 = default yo'q. Reja sahifasida boshlang'ich qiymat sifatida ishlatiladi.", verbose_name='Oylik reja default soni'),
        ),
    ]
