# Generated by Django 5.2.16 on 2026-07-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_kpidirection_default_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hokim',
            field=models.BooleanField(default=False, verbose_name='Hokim'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mahalla_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Mahalla nomi'),
        ),
    ]
